order:
  provider:
    id: "sellerapp_id"
  items:
    - id: "12391"
      quantity:
        selected:
          measure:
            value: "3000"
            unit: "INR"
  fulfillments:
    - id: "ff_123"
      type: "SIP"
      customer:
        person:
          id: "pan:arrpp7771n"
      agent:
        person:
          id: "euin:E52432"
        organization:
          creds:
            - id: "ARN-124567"
              type: "ARN"
            - id: "ARN-123456"
              type: "SUB_BROKER_ARN"
      stops:
        - time:
            schedule:
              frequency: "R6/2024-05-15/P1M"
  tags:
    - display: false
      descriptor:
        name: "BAP Terms of Engagement"
        code: "BAP_TERMS"
      list:
        - descriptor:
            name: "Static Terms (Transaction Level)"
            code: "STATIC_TERMS"
          value: "https://buyerapp.com/legal/ondc:fis14/static_terms?v=0.1"
        - descriptor:
            name: "Offline Contract"
            code: "OFFLINE_CONTRACT"
          value: "true"
