save-data:
  message_id: $.context.message_id
  transaction_id: $.context.transaction_id
  kyc_stage: $.message.order.xinput.head.index.cur
  form_submission_id: $.message.order.xinput.form.submission_id
  form_id: $.message.order.xinput.form.id
