order:
  id: "o1"
  provider:
    id: "sellerapp_id"
  items:
    - id: "12391"
      quantity:
        selected:
          measure:
            value: "3000"
            unit: "INR"
  fulfillments:
    - id: "ff_123"
      type: "SIP"
      customer:
        person:
          id: "pan:arrpp7771n"
      stops:
        - time:
            schedule:
              frequency: "R6/2024-05-15/P1M"
  quote:
    id: "q1"
    price:
      currency: "INR"
      value: "3000"
    breakup:
      - item:
          id: "12391"
          fulfillment_ids:
            - "ff_123"
        title: "SIP Installment"
        price:
          currency: "INR"
          value: "3000"
  payments:
    - type: "PRE_FULFILLMENT"
      collected_by: "BPP"
      status: "NOT-PAID"
      params:
        currency: "INR"
        amount: "3000"
  tags:
    - display: false
      descriptor:
        name: "BAP Terms of Engagement"
        code: "BAP_TERMS"
      list:
        - descriptor:
            name: "Static Terms (Transaction Level)"
            code: "STATIC_TERMS"
          value: "https://buyerapp.com/legal/ondc:fis14/static_terms?v=0.1"
