order:
  id: "o1"
  provider:
    id: "sellerapp_id"
  items:
    - id: "12391"
      fulfillment_ids:
        - "ff_123"
  fulfillments:
    - id: "ff_123"
      type: "SIP"
      state:
        descriptor:
          name: "SIP Payment Success"
          code: "PAYMENT_SUCCESS"
      tags:
        - descriptor:
            name: "Account Details"
            code: "ACCOUNT_DETAILS"
          list:
            - descriptor:
                name: "Folio Number"
                code: "FOLIO_NUMBER"
              value: "FN1234567890"
  payments:
    - type: "PRE_FULFILLMENT"
      collected_by: "BPP"
      status: "PAID"
      params:
        currency: "INR"
        amount: "3000"
        transaction_id: "TXN123456789"
