intent:
  category:
    descriptor:
      code: "MUTUAL_FUNDS"
  fulfillment:
    agent:
      organization:
        creds:
          - id: "ARN-125784"
            type: "ARN"
  tags:
    - display: false
      descriptor:
        name: "BAP Terms of Engagement"
        code: "BAP_TERMS"
      list:
        - descriptor:
            name: "Static Terms (Transaction Level)"
            code: "STATIC_TERMS"
          value: "https://buyerapp.com/legal/ondc:fis14/static_terms?v=0.1"
        - descriptor:
            name: "Offline Contract"
            code: "OFFLINE_CONTRACT"
          value: "true"
