codes:
  # Search flows (500-501)
  - code: 500
    action_id: search
    action: search
    default: FIS14/mutual-funds/2.1.0/search/default.yaml
    message_id: true
  - code: 501
    action_id: on_search
    action: on_search
    default: FIS14/mutual-funds/2.1.0/on_search/default.yaml
    message_id: false
    
  # SIP Creation flows (502-513)
  - code: 502
    action_id: select
    action: select
    default: FIS14/mutual-funds/2.1.0/select/default.yaml
    message_id: true
  - code: 503
    action_id: on_select
    action: on_select
    default: FIS14/mutual-funds/2.1.0/on_select/default.yaml
    message_id: false
  - code: 5021
    action_id: select_2
    action: select
    default: FIS14/mutual-funds/2.1.0/select_2/default.yaml
    message_id: true
  - code: 5031
    action_id: on_select_2
    action: on_select
    default: FIS14/mutual-funds/2.1.0/on_select_2/default.yaml
    message_id: false
  - code: 504
    action_id: init
    action: init
    default: FIS14/mutual-funds/2.1.0/init/default.yaml
    message_id: true
  - code: 505
    action_id: on_init
    action: on_init
    default: FIS14/mutual-funds/2.1.0/on_init/default.yaml
    message_id: false
  - code: 506
    action_id: confirm
    action: confirm
    default: FIS14/mutual-funds/2.1.0/confirm/default.yaml
    message_id: true
  - code: 507
    action_id: on_confirm
    action: on_confirm
    default: FIS14/mutual-funds/2.1.0/on_confirm/default.yaml
    message_id: false
  - code: 508
    action_id: on_status_unsolicited
    action: on_status
    default: FIS14/mutual-funds/2.1.0/on_status_unsolicited/default.yaml
    message_id: true
  - code: 509
    action_id: on_update_unsolicited
    action: on_update
    default: FIS14/mutual-funds/2.1.0/on_update_unsolicited/default.yaml
    message_id: false
