order:
  provider:
    id: provider_123
    descriptor:
      name: ABC Mutual Fund
  items:
    - id: item_123
      parent_item_id: scheme_138
      descriptor:
        name: ABC Mid Cap Fund - Regular - Growth
        code: SCHEME_PLAN
      creator:
        descriptor:
          name: ABC Mutual Fund
      fulfillment_ids:
        - ff_123
      quantity:
        selected:
          measure:
            value: "3000"
            unit: INR
      tags:
        - display: true
          descriptor:
            name: Plan Information
            code: PLAN_INFORMATION
          list:
            - descriptor:
                name: Consumer Terms & Conditions
                code: CONSUMER_TNC
              value: https://sellerapp.com/legal/ondc:fis14/consumer_tnc.html
        - display: true
          descriptor:
            name: Plan Identifiers
            code: PLAN_IDENTIFIERS
          list:
            - descriptor:
                name: ISIN
                code: ISIN
              value: INE123456789
            - descriptor:
                name: RTA Identifier
                code: RTA_IDENTIFIER
              value: 02BZ
            - descriptor:
                name: AMFI Identifier
                code: AMFI_IDENTIFIER
              value: "125487"
        - display: true
          descriptor:
            name: Plan Options
            code: PLAN_OPTIONS
          list:
            - descriptor:
                name: Plan
                code: PLAN
              value: REGULAR
            - descriptor:
                name: Option
                code: OPTION
              value: GROWTH
  xinput:
    required: false
    head:
      index:
        min: 0
        cur: 0
        max: 0
      headings:
        - APPLICATION_FORM
    form:
      id: form_123
      url: http://localhost:3001/forms/domain/account-opening-kyc/data?k=234sadf234
      mime_type: text/html
  fulfillments:
    - id: ff_123
      type: SIP
      customer:
        person:
          id: pan:arrpp7771n
      agent:
        person:
          id: euin:E52432
        organization:
          creds:
            - id: ARN-124567
              type: ARN
      stops:
        - time:
            schedule:
              frequency: R6/2024-05-15/P1M
      tags:
        - display: true
          descriptor:
            name: Thresholds
            code: THRESHOLDS
          list:
            - descriptor:
                name: Frequency
                code: FREQUENCY
              value: P1M
            - descriptor:
                name: Frequency Dates
                code: FREQUENCY_DATES
              value: "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28"
            - descriptor:
                name: Amount Minimum
                code: AMOUNT_MIN
              value: "5000"
            - descriptor:
                name: Amount Maximum
                code: AMOUNT_MAX
              value: "50000"
            - descriptor:
                name: Amount Multiples
                code: AMOUNT_MULTIPLES
              value: "1"
            - descriptor:
                name: Installments Count Minimum
                code: INSTALMENTS_COUNT_MIN
              value: "6"
            - descriptor:
                name: Installments Count Maximum
                code: INSTALMENTS_COUNT_MAX
              value: "12"
        - display: true
          descriptor:
            name: Folio
            code: FOLIO_INFORMATION
          list:
            - descriptor:
                name: Folio Number
                code: FOLIO_NUMBER
              value: FN001/32
            - descriptor:
                name: Holding Pattern
                code: HOLDING_PATTERN
              value: SINGLE
            - descriptor:
                name: Holder Name
                code: HOLDER_NAME
              value: John Doe
            - descriptor:
                name: Created On
                code: CREATED_ON
              value: "25/11/2019"
            - descriptor:
                name: Email Address for 2FA
                code: 2FA_EMAIL_ADDRESS_MASKED
              value: "****john@gmail.com"
            - descriptor:
                name: Mobile Number for 2FA
                code: 2FA_MOBILE_NUMBER_MASKED
              value: "***9345"
  payments:
    - collected_by: BPP
      type: PRE_FULFILLMENT
    - collected_by: BPP
      type: PRE_FULFILLMENT
      tags:
        - descriptor:
            name: Payment Method
            code: PAYMENT_METHOD
          list:
            - descriptor:
                code: MODE
              value: SKIP_PAYMENT
    - collected_by: BPP
      type: PRE_FULFILLMENT
      tags:
        - descriptor:
            name: Payment Method
            code: PAYMENT_METHOD
          list:
            - descriptor:
                code: MODE
              value: UPI_AUTOPAY
            - descriptor:
                code: AUTH
              value: DEBIT
            - descriptor:
                code: VPA
              value: user@example
